on: push
name: Build and Publish
jobs:
  all:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Automated releases for npm packages.
      uses: mikeal/merge-release@master
